### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by brendanevans**
This is a rewrite of the Messages move commands. It add them all to a Move group which uses more meaningfully named sub commands and aliases.
It also adds a range/between option for move select blocks of messages.

### CODE REVIEW

**Comment by DPR-Sanchez** [comment]
Thank you for the pull request, please remedy the indicated matters in the lines listed below before the pull is accepted.

158-166, replace with `all(message.id == message.id == first_message_id, message.id == second_message_id)` statement due to it being more concise.
115, 139, change `Messages.move_action` to `self.move_action`
158 & others, change camel case to snake case to match surrounding code and PEP-8

Additionally, please run the code through a PEP 8 auto-formatter

**Comment by brendanevans** [comment]
All feedback has been applied and committed.

**Comment by FrostByte266** [comment]
Looking good! Just one more thing before we merge, on lines 115 and 139 on messages.py, you're still passing self in, which will error because it implicitly will pass self. Just remove that part and it will be all good to go.

**Comment by brendanevans** [comment]
This has been corrected in the latest commit.

**Pull request merged**
